# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BifidDecryption.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(709, 491)
        self.decryptbutton = QtWidgets.QPushButton(Dialog)
        self.decryptbutton.setGeometry(QtCore.QRect(300, 290, 111, 41))
        self.decryptbutton.setStyleSheet("QPushButton {\n"
                                         "  padding: 8px 25px;\n"
                                         "\n"
                                         "  text-align: center;\n"
                                         "  outline: none;\n"
                                         "  color: #fff;\n"
                                         "  background-color:     #008000;\n"
                                         "  border: none;\n"
                                         "  border-radius: 15px;\n"
                                         "font: 15pt \"Rockwell\";\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {background-color: #006400}")
        self.decryptbutton.setObjectName("decryptbutton")
        self.decryptbutton.clicked.connect(self.Decryption)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 711, 491))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/Columnar.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 40, 301, 51))
        self.label_3.setStyleSheet("color: rgb(253, 250, 255);\n"
                                   "font: 30pt \"Rockwell\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(270, 50, 291, 51))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.plaintext = QtWidgets.QTextBrowser(Dialog)
        self.plaintext.setGeometry(QtCore.QRect(100, 380, 521, 41))
        self.plaintext.setStyleSheet("  padding: 5px 20px;\n"
                                     "\n"
                                     "  text-align: center;\n"
                                     "  outline: none;\n"
                                     "  background-color:     #f7f7f7;\n"
                                     "  border: none;\n"
                                     "  border-radius: 15px;\n"
                                     "font: 14pt \"Futura\";")
        self.plaintext.setObjectName("Plaintext")
        self.Ciphertext_2 = QtWidgets.QLineEdit(Dialog)
        self.Ciphertext_2.setGeometry(QtCore.QRect(110, 140, 491, 41))
        self.Ciphertext_2.setStyleSheet("QLineEdit{\n"
                                        "  padding: 8px 20px;\n"
                                        "\n"
                                        "  text-align: center;\n"
                                        "  outline: none;\n"
                                        "  background-color:     #f7f7f7;\n"
                                        "  border: 2px solid rgb(194, 191, 196);\n"
                                        "  border-radius: 15px;\n"
                                        "font: 14pt \"Futura\";\n"
                                        "}\n"
                                        "QLineEdit:hover{\n"
                                        "border: 2px solid rgb(70, 69, 71);\n"
                                        "}\n"
                                        "QlineEdit:active{\n"
                                        "border: 2px solid rgb(0, 116, 0);\n"
                                        "}")
        self.Ciphertext_2.setObjectName("Ciphertext_2")
        self.key = QtWidgets.QLineEdit(Dialog)
        self.key.setGeometry(QtCore.QRect(110, 200, 251, 41))
        self.key.setStyleSheet("QLineEdit{\n"
                               "  padding: 8px 20px;\n"
                               "\n"
                               "  text-align: center;\n"
                               "  outline: none;\n"
                               "  background-color:     #f7f7f7;\n"
                               "  border: 2px solid rgb(194, 191, 196);\n"
                               "  border-radius: 15px;\n"
                               "font: 14pt \"Futura\";\n"
                               "}\n"
                               "QLineEdit:hover{\n"
                               "border: 2px solid rgb(70, 69, 71);\n"
                               "}\n"
                               "QlineEdit:active{\n"
                               "border: 2px solid rgb(0, 116, 0);\n"
                               "}")
        self.key.setObjectName("key")
        self.label.raise_()
        self.decryptbutton.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.plaintext.raise_()
        self.Ciphertext_2.raise_()
        self.key.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.decryptbutton.setText(_translate("Dialog", "Decrypt"))
        self.label_3.setText(_translate("Dialog", "Bifid Cipher"))
        self.label_5.setText(_translate("Dialog", "_____________________________"))
        self.plaintext.setPlaceholderText(_translate("Dialog", "The Plaintext (Result)"))
        self.Ciphertext_2.setPlaceholderText(_translate("Dialog", "Enter the Ciphertext:"))
        self.key.setPlaceholderText(_translate("Dialog", "Enter the Key e.g. 'do it'"))

    def Decryption(self):
        Alphabets = list("ABCDEFGHIKLMNOPQRSTUVWXYZ")

        CipherText = self.Ciphertext_2.text().replace(" ", "").upper() #.replace("J", "I")
        Key = self.key.text().upper() #.replace(" ", "") #.replace("J", "I")
        MatrixOne = []

        for c in Key:

            if c in Alphabets and c not in MatrixOne:
                MatrixOne.append(c)

        for c in Alphabets:

            if c not in MatrixOne:
                MatrixOne.append(c)

        FinalMatrix = []
        i = 0

        for Rows in range(5):

            rw = []

            for Column in range(5):
                rw.append(MatrixOne[i])
                i += 1

            FinalMatrix.append(rw)

        location = []

        for lt in CipherText:
            x = [(a + 1, b + 1) for a, row in enumerate(FinalMatrix) for b, j in enumerate(row) if j == lt]

            location.append(x[0])

        Result = [(str(i[0]), str(i[1])) for i in location]

        Result = ["".join(i) for i in Result]
        Result = "".join(Result)
        Rows = Result[:int(len(Result) / 2)]
        Columns = Result[int(len(Result) / 2):]
        Plaintext = ""

        for i in range(len(Rows)):
            Plaintext += FinalMatrix[int(Rows[i]) - 1][int(Columns[i]) - 1]

        self.plaintext.setText(Plaintext)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
