# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PolybiusEncryption.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(709, 491)
        self.encryptbutton = QtWidgets.QPushButton(Dialog)
        self.encryptbutton.setGeometry(QtCore.QRect(290, 250, 111, 41))
        self.encryptbutton.setStyleSheet("QPushButton {\n"
                                         "  padding: 8px 25px;\n"
                                         "\n"
                                         "  text-align: center;\n"
                                         "  outline: none;\n"
                                         "  color: #fff;\n"
                                         "  background-color:     #008000;\n"
                                         "  border: none;\n"
                                         "  border-radius: 15px;\n"
                                         "font: 15pt \"Rockwell\";\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {background-color: #006400}")
        self.encryptbutton.setObjectName("encryptbutton")
        self.encryptbutton.clicked.connect(self.Encryption)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 711, 491))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/Polybius.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 40, 301, 51))
        self.label_3.setStyleSheet("color: rgb(253, 250, 255);\n"
                                   "font: 30pt \"Rockwell\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(240, 50, 291, 51))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.Ciphertext = QtWidgets.QTextBrowser(Dialog)
        self.Ciphertext.setGeometry(QtCore.QRect(100, 360, 521, 41))
        self.Ciphertext.setStyleSheet("  padding: 5px 20px;\n"
                                      "\n"
                                      "  text-align: center;\n"
                                      "  outline: none;\n"
                                      "  background-color:     #f7f7f7;\n"
                                      "  border: none;\n"
                                      "  border-radius: 15px;\n"
                                      "font: 14pt \"Futura\";")
        self.Ciphertext.setObjectName("Ciphertext")
        self.Plaintext = QtWidgets.QLineEdit(Dialog)
        self.Plaintext.setGeometry(QtCore.QRect(110, 140, 491, 41))
        self.Plaintext.setStyleSheet("QLineEdit{\n"
                                     "  padding: 8px 20px;\n"
                                     "\n"
                                     "  text-align: center;\n"
                                     "  outline: none;\n"
                                     "  background-color:     #f7f7f7;\n"
                                     "  border: 2px solid rgb(194, 191, 196);\n"
                                     "  border-radius: 15px;\n"
                                     "font: 14pt \"Futura\";\n"
                                     "}\n"
                                     "QLineEdit:hover{\n"
                                     "border: 2px solid rgb(70, 69, 71);\n"
                                     "}\n"
                                     "QlineEdit:active{\n"
                                     "border: 2px solid rgb(0, 116, 0);\n"
                                     "}")
        self.Plaintext.setObjectName("Plaintext")
        self.label.raise_()
        self.encryptbutton.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.Ciphertext.raise_()
        self.Plaintext.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.encryptbutton.setText(_translate("Dialog", "Encrypt"))
        self.label_3.setText(_translate("Dialog", "Polybius Cipher"))
        self.label_5.setText(_translate("Dialog", "________________________________________"))
        self.Ciphertext.setPlaceholderText(_translate("Dialog", "The Ciphertext (Result)"))
        self.Plaintext.setPlaceholderText(_translate("Dialog", "Enter the Plaintext:"))

    def Encryption(self):
        Alphabets = "abcdefghiklmnopqrstuvwxyz"
        PlainText = self.Plaintext.text().lower()
        CipherText = ""

        for letter in PlainText:

            if letter == "j":
                Row, Col = 2, 4
                CipherText += str(Row) + str(Col) + " "

            elif letter not in Alphabets:
                continue

            else:

                Row = int((Alphabets.find(letter) / 5) + 1)
                Col = (Alphabets.find(letter) % 5) + 1
                CipherText += str(Row) + str(Col) + " "

        self.Ciphertext.setText(CipherText)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
